name: zeotap_sheets_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  csv: ^6.0.0
  file_picker: ^9.0.2
  flutter:
    sdk: flutter
  math_expressions: ^2.6.0
  path_provider: ^2.1.5
  velocity_x: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
